<?php

define('NUMBER_LANGUAGES',32);
define('NUMBER_CLASSES',8);

define('LNG_FRENCH',0);
define('LNG_ENGLISH',1);
define('LNG_ARABIC',2);
define('LNG_RUSSIAN',3);
define('LNG_GERMAN',4);
define('LNG_ITALIAN',5);
define('LNG_GREEK',6);
define('LNG_SPANISH',7);
define('LNG_PERSIAN',8);
define('LNG_CHINESE',9);
define('LNG_TURKISH',10);
define('LNG_FINNISH',11);
define('LNG_HEBREW',12);
define('LNG_PORTUGUESE',13);
define('LNG_ROMAN',14);
define('LNG_POLISH',15);
define('LNG_HUNGARIAN',16);
define('LNG_DUTCH',17);
define('LNG_IRISH',18);
define('LNG_SWEDISH',19);
define('LNG_LATIN',20);
define('LNG_ICELANDIC',21);
define('LNG_HINDI',22);
define('LNG_CZECH',23);
define('LNG_MALAYSIAN',24);
define('LNG_BULGARIAN',25);
define('LNG_NORWEGIAN',26);
define('LNG_ALBANIAN',27);
define('LNG_URDU',28);
define('LNG_THAI',29);
define('LNG_INDONESIAN',30);
define('LNG_DANISH',31);

?>